---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/,http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/

---
spring:
  profiles: lab-5-subject
words: I,You,He,She,It
  
---
spring:
  profiles: lab-5-verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: lab-5-article
words: a,the

---
spring:
  profiles: lab-5-adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: lab-5-noun
words: boat,book,vote,seat,backpack,partition,groundhog
